create table if not exists public.assessorados (
  id bigint generated by default as identity primary key,
  nome text not null,
  funcao text not null,
  foto_url text not null default '',
  instagram_url text,
  video_url text,
  destaque boolean not null default false,
  ativo boolean not null default true,
  ordem integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.assessorados enable row level security;

drop policy if exists "assessorados_public_read" on public.assessorados;
create policy "assessorados_public_read"
on public.assessorados for select
to anon
using (ativo = true);

drop policy if exists "assessorados_authenticated_manage" on public.assessorados;
create policy "assessorados_authenticated_manage"
on public.assessorados for all
to authenticated
using (true)
with check (true);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists assessorados_set_updated_at on public.assessorados;
create trigger assessorados_set_updated_at
before update on public.assessorados
for each row execute procedure public.set_updated_at();

insert into storage.buckets (id, name, public)
values ('assessorados', 'assessorados', true)
on conflict (id) do update set public = true;

drop policy if exists "assessorados_images_public_read" on storage.objects;
create policy "assessorados_images_public_read"
on storage.objects for select
to public
using (bucket_id = 'assessorados');

drop policy if exists "assessorados_images_authenticated_insert" on storage.objects;
create policy "assessorados_images_authenticated_insert"
on storage.objects for insert
to authenticated
with check (bucket_id = 'assessorados');

drop policy if exists "assessorados_images_authenticated_update" on storage.objects;
create policy "assessorados_images_authenticated_update"
on storage.objects for update
to authenticated
using (bucket_id = 'assessorados')
with check (bucket_id = 'assessorados');

drop policy if exists "assessorados_images_authenticated_delete" on storage.objects;
create policy "assessorados_images_authenticated_delete"
on storage.objects for delete
to authenticated
using (bucket_id = 'assessorados');

insert into public.assessorados (nome, funcao, foto_url, instagram_url, video_url, destaque, ativo, ordem)
select * from (values
  ('Diego Marçal', 'Cantor / Preletor', '/assets/img/diegomarcal.jpeg', null::text, 'https://www.instagram.com/reel/DXH3Vx2j_8y/?igsh=MnhqN3A1cmptdHR5', true, true, 1),
  ('Paloma César', 'Preletora', '/assets/img/Paloma%20C%C3%A9sar.jpeg', null::text, null::text, false, true, 2),
  ('Tainah Oliver', 'Cantora', '/assets/img/Tainah%20Oliver.jpeg', null::text, null::text, false, true, 3),
  ('Eduardo Silva', 'Cantor', '/assets/img/Eduardo%20Silva.jpeg', null::text, null::text, false, true, 4),
  ('Irmãs Miguel', 'Dupla', '/assets/img/Irm%C3%A3s%20Miguel.jpeg', null::text, null::text, false, true, 5),
  ('Marilene e Gabriela', 'Dupla', '/assets/img/Marilene%20e%20Gabriela.jpeg', null::text, null::text, false, true, 6),
  ('Natanael Santos', 'Preletor', '/assets/img/Natanael%20Santos.jpeg', null::text, null::text, false, true, 7)
) as seed(nome, funcao, foto_url, instagram_url, video_url, destaque, ativo, ordem)
where not exists (select 1 from public.assessorados);
